-- ============================================================
-- GOAL TRACKER BOT — DATABASE SCHEMA
-- Run this in your Supabase SQL Editor in order.
-- ============================================================


-- -------------------------------------------------------
-- 1. USERS
-- Stores one record per unique person.
-- A user can connect via Telegram, WhatsApp, or both.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone            TEXT UNIQUE,                      -- used to link Telegram + WhatsApp
    first_name       TEXT,
    username         TEXT,
    timezone         TEXT DEFAULT 'Africa/Lagos',
    preferred_platform TEXT DEFAULT 'telegram',       -- 'telegram' | 'whatsapp' | 'both'
    created_at       TIMESTAMPTZ DEFAULT NOW()
);


-- -------------------------------------------------------
-- 2. USER PLATFORMS
-- Links a user to their Telegram and/or WhatsApp identity.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_platforms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users(id) ON DELETE CASCADE,
    platform     TEXT NOT NULL,                        -- 'telegram' | 'whatsapp'
    platform_id  TEXT NOT NULL,                        -- telegram chat_id OR whatsapp number e.g. whatsapp:+2348012345678
    chat_id      TEXT,                                 -- telegram chat_id (null for whatsapp)
    linked_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(platform, platform_id)
);


-- -------------------------------------------------------
-- 3. GOALS
-- Each user can have multiple long-term goals.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS goals (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users(id) ON DELETE CASCADE,
    goal_text    TEXT NOT NULL,
    category     TEXT DEFAULT 'general',               -- e.g. 'health', 'career', 'finance'
    priority     INTEGER DEFAULT 1,                    -- 1 = highest
    is_active    BOOLEAN DEFAULT TRUE,
    target_date  DATE,                                 -- optional deadline
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);


-- -------------------------------------------------------
-- 4. DAILY ACTIVITIES
-- AI-generated daily plan per user per day.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS daily_activities (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT REFERENCES users(id) ON DELETE CASCADE,
    content       TEXT,                                -- AI-generated plan text
    activity_date DATE DEFAULT CURRENT_DATE,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (user_id, activity_date)
);


-- -------------------------------------------------------
-- 5. CHECK-IN RESPONSES
-- Stores what users reply during the day's check-ins.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS checkin_responses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT REFERENCES users(id) ON DELETE CASCADE,
    checkin_time  TEXT NOT NULL,                       -- '9am' | '12pm' | '3pm' | '6pm'
    response_text TEXT,
    response_date DATE DEFAULT CURRENT_DATE,
    platform      TEXT,                                -- which platform they replied on
    created_at    TIMESTAMPTZ DEFAULT NOW()
);


-- -------------------------------------------------------
-- 6. STREAKS
-- Tracks each user's consecutive active days.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS streaks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    current_streak   INTEGER DEFAULT 0,
    longest_streak   INTEGER DEFAULT 0,
    last_active_date DATE,
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);


-- -------------------------------------------------------
-- 7. WEEKLY SUMMARIES
-- AI-generated summary every Sunday evening.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS weekly_summaries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users(id) ON DELETE CASCADE,
    week_start   DATE NOT NULL,
    week_end     DATE NOT NULL,
    content      TEXT,                                 -- AI-generated summary text
    created_at   TIMESTAMPTZ DEFAULT NOW()
);


-- -------------------------------------------------------
-- INDEXES — speeds up common lookups
-- -------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_goals_user_id          ON goals(user_id);
CREATE INDEX IF NOT EXISTS idx_daily_activities_user  ON daily_activities(user_id, activity_date);
CREATE INDEX IF NOT EXISTS idx_checkin_user_date      ON checkin_responses(user_id, response_date);
CREATE INDEX IF NOT EXISTS idx_user_platforms_lookup  ON user_platforms(platform, platform_id);

-- -------------------------------------------------------
-- 8. LINK TOKENS
-- Temporary tokens for linking Telegram ↔ WhatsApp accounts.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS link_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    token      TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);